"""Inicialización de la base de datos

Revision ID: c9d567ea6ff0
Revises: 
Create Date: 2025-03-06 13:14:46.680545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d567ea6ff0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('institucion', sa.String(length=200), nullable=False),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('antecedentes', sa.Text(), nullable=True),
    sa.Column('actividad', sa.Text(), nullable=False),
    sa.Column('finalidad', sa.String(length=100), nullable=True),
    sa.Column('permiso_file', sa.String(length=200), nullable=True),
    sa.Column('integrantes_file', sa.String(length=200), nullable=True),
    sa.Column('pernoctar', sa.Boolean(), nullable=True),
    sa.Column('sitios', sa.String(length=200), nullable=True),
    sa.Column('infraestructuras', sa.String(length=200), nullable=True),
    sa.Column('requiere_ayudantes', sa.Boolean(), nullable=True),
    sa.Column('requiere_pasajes', sa.Boolean(), nullable=True),
    sa.Column('requiere_alojamiento', sa.Boolean(), nullable=True),
    sa.Column('alojamiento_detalles', sa.Text(), nullable=True),
    sa.Column('requiere_vianda', sa.Boolean(), nullable=True),
    sa.Column('otras_aclaraciones', sa.Text(), nullable=True),
    sa.Column('responsable_nombre', sa.String(length=100), nullable=False),
    sa.Column('responsable_dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('email_alternativo', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('direccion_postal', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fechas_reservadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cantidad_personas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fechas_reservadas')
    op.drop_table('reservations')
    # ### end Alembic commands ###
